language: python
sudo: false
services:
  - cassandra
python:
  - "2.7"
  - "3.3"
  - "3.4"
# Suspended "3.5" on 6 July because Cassandra isn't working on Travis with Python 3.5
#  - apparently the Cassandra driver doesn't support Python 3.5, maybe it will someday
#  - "3.5"
install: pip install -r requirements.txt
script: python -m unittest discover eventsourcingtests -v
