language: python
sudo: false
services:
  - cassandra
python:
  - "2.7"
  - "3.3"
  - "3.4"
#  - "3.5"   # Suspended on 6 July because Travis Cassandra isn't working on this version today.
install: pip install -r requirements.txt
script: python -m unittest discover eventsourcingtests -v
