language: python
services:
  - cassandra
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
install: pip install -r requirements.txt
script: python -m unittest discover eventsourcingtests -v
