language: python
sudo: false
services:
  - cassandra
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
# Suspended "3.5" on 6 July because Cassandra isn't working on Travis with Python 3.5.
# Apparently the Cassandra driver doesn't support Python 3.5, maybe it will someday.
#  - "3.5"

install:
- pip install -U pip
- pip install -r requirements.txt
- pip install python-coveralls

script:
- coverage run -m unittest discover eventsourcing.tests -v

after_success:
- coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dcfa1ee023ab5059b4d5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
