language: python
sudo: false
services:
  - cassandra
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
- pip install -U pip
- pip install -e .[test]
- pip install python-coveralls

env:
  global:
    - CASSANDRA_PROTOCOL_VERSION=2
    - CASSANDRA_HOSTS=127.0.0.1

script:
- coverage run -m unittest discover eventsourcing.tests -v

after_success:
- coveralls
